#
# Run Docker containers for End-to-End test on local environment.
#
version: "3.7"

services:
  selenium-hub:
    image: selenium/hub:3.141.59-20210105
    ports:
      - "4444:4444"
  selenium-chrome:
    image: selenium/node-chrome-debug:3.141.59-20210105
    shm_size: '2gb'
    ports:
      - "15900:5900"
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium-hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_INSTANCES: 10
      NODE_MAX_SESSION: 10
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1200

networks:
  default:
    name: end-to-end-test
